### ISSUE TITLE
Save Data Button not visible if too many columns selected

### ISSUE THREAD

**Issue by daramann** [leematthewshome/Qlik-Sense-Live-Table#1]
This might fix:
`id="dataEntry" style="width:500pt;height:80%;overflow: auto;" `

**Comment by leematthewshome** [comment]
Thanks for picking this up. 
That seems to be a fair solution. It causes the form to always display at 80% of the parent dive height, even when the fields available for edit only might take up 40%. But that does not look too horrible.
At this stage this is better than losing the ability to click on the save button. If i can work out a more graceful solution I will use that in future.

**Comment by daramann** [comment]
Glad to help, good job by the way, really looking forward for future releases.
