### ISSUE TITLE
Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by ricardokruger** [leematthewshome/Qlik-Sense-Live-Table#2]
I'm trying to test this extension but for some reason it's not working on my desktop environment.
It seems that the REST API server is running correctly but when I open the QVF sample file, nothing happens in the writeback sheet.
So I'm started debbuging it whit the chrome developer tools and found this error.

_Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode_ - **LiveTable.js:39**

Line 39 has this code
`let fetchData = { `

How can I fix it?
I'm using the Qlik Sense Desktop June 2018 for test and development.

**Comment by leematthewshome** [comment]
What database are you using?
If you are using the sqlite database
 - did you install sqlite libraries for Python?
 - did you edit the connection details in the python code, ie.
            conn = sqlite3.connect('C:\\liveTableREST\\testdata\\DemoData.sqlite')
  - try navigating with a browser to [Your REST URL]\test and you should see a JSON response. 
     If that is not working then the extension in Qlik will not work. Get that working first.

**Comment by kurouka** [comment]
Hello

Edit: This seems to be fixed by changing "let" to "var" in the live table javascript file. "Let" defines "fetchData" in three places, changing them to "var" removes the error

**Comment by leematthewshome** [comment]
Thank you for the update. I have modified the code on Github to use Var rather than Let.
