### ISSUE TITLE
I cannot drag and drop the extension on April 2019

### ISSUE THREAD

**Issue by simonaubertbd** [leematthewshome/Qlik-Sense-Live-Table#4]
Hello,

I tried the extension on :
-Nov 2018 : I can drag and drop the extension
-April 2019 : I cannot use it anymore, the drag and drop is ko.

Can you please fix it? We plan to upgrade our Qlik Sense install

**Comment by leematthewshome** [comment]
Please try the latest code from Github. I was making changes just last week and was testing on the latest release of Qlik Sense without problem.


Lee Matthews
Presales Team Lead, ANZ

Direct: +61 3 8614 1319
Mobile: +61 400 892 602
Email:  Lee.Matthews@qlik.com

Qlik
Level 14, 520 Collins St
Melbourne Victoria
3000

qlik.com<http://www.qlik.com/>

**Comment by simonaubertbd** [comment]
Hello Lee,

Thanks for the fast answer, especially on your week-end.

I spend a few time on this. it was due to not the release (nov18 versus apr19) but server versus desktop. So, I replace every occurence of "let" by "var" in the code and I could drag and drop. Do you think it would be a good idea to change your source code this way, in order to make the extension "desktop compatible"?

I wrote an idea about that issue here : 
https://community.qlik.com/t5/Qlik-Sense-Enterprise-Ideas/Update-QS-Desktop-to-work-like-QS-server-internal-chrome/idi-p/1576617

Best regards,

Simon

**Comment by lmeier1992** [comment]
Hello Lee,

I have exactly the same problem with QlikSense April 2019 version. The server site is working, but the extension not. Where can I find the code with your changes from last week? Last change on github is from July 17, 2018.

Best regrads,
Lisa

**Comment by simonaubertbd** [comment]
Lisa, you have to edit the extension and replace every occurence of "let" by "var" in the code

**Comment by lmeier1992** [comment]
Simon, I did, but it does not fix it

**Comment by leematthewshome** [comment]
I just modified the code on Github to use Var rather than Let. I tested the extension with QSD April 2019 and it worked fine.
